### ISSUE TITLE
How were these converted?

### ISSUE THREAD

**Issue by pritster5** [teddy-ROxPin/TA_Sigma_Searches#39]
I'm currently looking for a general way to convert SIGMA rules to Splunk queries, so how was this conversion done? 

Is there an automatic way to do it or is it all manual?

**Comment by teddy-ROxPin** [comment]
I use 'sigmac' which is a tool included in the Sigma repo to convert the rules to Splunk queries. There is a replacement for 'sigmac' now - https://github.com/SigmaHQ/pySigma but I haven't looked into that yet. There is also a web-based converter available at https://uncoder.io/

**Comment by pritster5** [comment]
Sorry I actually meant the opposite, how did you convert from Splunk to Sigma?
